### ISSUE TITLE
记移动端开发中常见的坑 😀  

### ISSUE THREAD

**Issue by fanqidong** [fanqidong/blog-backstage#18]
[pixiv: 65567135]: # 'https://view.moezx.cc/images/2018/06/20/kai-di-chen-short-hair-cprd.jpg'  

做过很多移动端H5的项目，在此期间也出现过很多关于机型、`Android`和`iOS`的兼容性问题，就此准备写下这篇文章，记录问题所在和解决过程，以便大家日后能够避免那些坑。    

# 废话不多说，撸起袖子加油干

##  上下拉动滚动条时卡顿、慢
一般这种情况出现在iOS机型上，解决方案：
```css
body {
 -webkit-overflow-scrolling: touch;
 overflow-scrolling: touch;
}
````
##  ios safari时间显示问题。

之前做倒计时设置new Date日期格式的时候，在ios中的safari中发现显示效果与其他浏览器不一致，找了多方面原因，发现是iOS识别“-”格式时间会显示NaN, 把“-”换成“/”就可以解决了。
```javascript

 let time = new Date("year-month-day");  //iOS不兼容
 let allTime = new Date("year/month/day"); //兼容Android和iOS

```

## 移动端图片上传图片  
```
input需要设置accept="image/*" multiple等属性,兼容低端机的问题

```

## 页面长按出现内容时，需要禁止用户选中文本复制干扰
```css
Element {-webkit-user-select:none;
  -moz-user-select:none;
  -khtml-user-select:none;
   user-select:none;
}
```
以上css对Android不起作用，需要采用js的方法禁止默认行为  

```javascript
document.oncontextmenu = function (e) {
        var e = e || event;
        e.preventDefault();
 };
```
所以在碰到这种需求时，`css`和`js`都写才可以兼容此问题  

## ios和android下触摸元素时出现半透明蓝色底 ,添加以下css代码去除  

```css 
Element {
  -webkit-tap-highlight-color:rgba(255,255,255,0)
}
``` 
## `IE10`里面的`input`会出现一个叉号 
```css 
input:-ms-clear{display:none;}
```
## ios中`input`有默认的圆角。css去除如下：
```css
input,
textarea {
  border: 0;
  -webkit-appearance: none; 
}
```

> 写在最后，以上是我工作中遇到常见的移动端兼容解决方案，后续如果遇到其他问题再继续更新。
